upstream actions_stub_app {
  server app:8080;
}

server {
  listen 80;
  server_name _;

  location /health {
    proxy_pass http://actions_stub_app/health;
  }

  location / {
    proxy_pass http://actions_stub_app/;
  }

  location /content/ {
    alias /usr/share/nginx/html/;
  }
}
